### ISSUE TITLE
pip install --upgrade orionx-api-client (error)

### ISSUE THREAD

**Issue by magentochile** [itolosa/orionx-api-client#12]
Estimado Itolosa,

Tengo el siguiente error en la consola. Por favor me puedes guiar que puede ser:

[root@centos-s-4vcpu-XXXXX html]# pip install --upgrade orionx-api-client
Collecting orionx-api-client
  Downloading orionx-api-client-1.0.5.tar.gz
Collecting requests==2.18.4 (from orionx-api-client)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 3.8MB/s 
Collecting six==1.11.0 (from orionx-api-client)
  Downloading six-1.11.0-py2.py3-none-any.whl
Requirement already up-to-date: ujson==1.35 in /usr/lib64/python2.7/site-packages (from orionx-api-client)
Collecting graphql-core==2.0 (from orionx-api-client)
  Downloading graphql_core-2.0-py2.py3-none-any.whl (202kB)
    100% |████████████████████████████████| 204kB 3.0MB/s 
Collecting pygql==0.1.4 (from orionx-api-client)
  Downloading pygql-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hdgRwW/pygql/setup.py", line 35, in <module>
        packages=find_packages(include=["pygql*"]),
    TypeError: find_packages() got an unexpected keyword argument 'include'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hdgRwW/pygql/

[root@centos-s-4vcpu-XXXXX html]# python --version
Python 2.7.5

Saludos y gracias!

Boris Durán R.

**Comment by itolosa** [comment]
Al parecer es un bug que tiene relación con la versión de setuptools. No lo pude replicar, pero te recomiendo que actualices la librería a la última versión y pruebes nuevamente:
```
$ pip install -U setuptools
$ pip install -U orionx-api-client
```

**Comment by magentochile** [comment]
Estimado Itolosa!!! acá dejo mi consola de respuesta:

[root@centos-s-4vcpu-XXXXX ~]# pip install -U setuptools
Collecting setuptools
  Downloading setuptools-39.0.1-py2.py3-none-any.whl (569kB)
    100% |████████████████████████████████| 573kB 1.1MB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 0.9.8
    Uninstalling setuptools-0.9.8:
      Successfully uninstalled setuptools-0.9.8
Successfully installed setuptools-39.0.1

/////////// aplicamos orionx-api-client //////////

[root@centos-s-4vcpu-XXXXX ~]# pip install -U orionx-api-client
Collecting orionx-api-client
  Using cached orionx-api-client-1.0.5.tar.gz
Collecting requests==2.18.4 (from orionx-api-client)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting six==1.11.0 (from orionx-api-client)
  Using cached six-1.11.0-py2.py3-none-any.whl
Requirement already up-to-date: ujson==1.35 in /usr/lib64/python2.7/site-packages (from orionx-api-client)
Collecting graphql-core==2.0 (from orionx-api-client)
  Using cached graphql_core-2.0-py2.py3-none-any.whl
Collecting pygql==0.1.4 (from orionx-api-client)
  Using cached pygql-0.1.4.tar.gz
Collecting fake-useragent==0.1.8 (from orionx-api-client)
  Downloading fake-useragent-0.1.8.tar.gz
Collecting futures (from orionx-api-client)
  Downloading futures-3.2.0-py2-none-any.whl
Collecting certifi>=2017.4.17 (from requests==2.18.4->orionx-api-client)
  Downloading certifi-2018.1.18-py2.py3-none-any.whl (151kB)
    100% |████████████████████████████████| 153kB 3.7MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests==2.18.4->orionx-api-client)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 4.4MB/s 
Collecting idna<2.7,>=2.5 (from requests==2.18.4->orionx-api-client)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 6.0MB/s 
Collecting urllib3<1.23,>=1.21.1 (from requests==2.18.4->orionx-api-client)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 4.6MB/s 
Collecting rx>=1.6.0 (from graphql-core==2.0->orionx-api-client)
  Downloading Rx-1.6.1-py2.py3-none-any.whl (179kB)
    100% |████████████████████████████████| 184kB 1.8MB/s 
Collecting promise>=2.1 (from graphql-core==2.0->orionx-api-client)
  Downloading promise-2.1-py2-none-any.whl
Collecting typing (from promise>=2.1->graphql-core==2.0->orionx-api-client)
  Downloading typing-3.6.4-py2-none-any.whl
Installing collected packages: certifi, chardet, idna, urllib3, requests, six, rx, typing, promise, graphql-core, futures, pygql, fake-useragent, orionx-api-client
  Found existing installation: chardet 2.2.1
    Uninstalling chardet-2.2.1:
      Successfully uninstalled chardet-2.2.1
  Found existing installation: urllib3 1.10.2
    Uninstalling urllib3-1.10.2:
      Successfully uninstalled urllib3-1.10.2
  Found existing installation: requests 2.6.0
    DEPRECATION: Uninstalling a distutils installed project (requests) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling requests-2.6.0:
      Successfully uninstalled requests-2.6.0
  Found existing installation: six 1.9.0
    Uninstalling six-1.9.0:
      Successfully uninstalled six-1.9.0
  Running setup.py install for pygql ... done
  Running setup.py install for fake-useragent ... done
  Running setup.py install for orionx-api-client ... done
Successfully installed certifi-2018.1.18 chardet-3.0.4 fake-useragent-0.1.8 futures-3.2.0 graphql-core-2.0 idna-2.6 orionx-api-client-1.0.5 promise-2.1 pygql-0.1.4 requests-2.18.4 rx-1.6.1 six-1.11.0 typing-3.6.4 urllib3-1.22

¿Estamos ok? 

Estoy tratando de llamar la API de orionx para calcular el valor de un producto o productos en pesos chilenos, y lo convierta a cryptomonedas según el valor indicado en orionx.com. ¿alguna sugerencia o ejemplo extra?

Por ejemplo en simplepay.cl puedo llamar al valor de Ethereum así:
https://simplepay.cl/api/exchange/eth-clp

{"buy":217300,"sell":224037,"spread":6737,"mid":220669,"market":216201,"stats":{"fromDate":1522543020000,"toDate":1522629420000,"volume":35.0951551,"volumeSecondary":0.07965236,"count":105,"variation":-3.953780747308988,"average":227873,"high":239060,"low":216201,"open":225101,"close":216201}}

O para Luka así:
https://simplepay.cl/api/exchange/luk-clp

{"buy":331,"sell":345,"spread":14,"mid":338,"market":345,"stats":{"fromDate":1522543020000,"toDate":1522629420000,"volume":35406.39760967,"volumeSecondary":0.12814253,"count":474,"variation":-10.15625,"average":365,"high":395,"low":321,"open":384,"close":345}}

Saludos y gracias,

Boris Durán R.

**Comment by itolosa** [comment]
Al parecer no hubieron problemas luego de actualizar setuptools. Con respecto a tu duda puedo sugerirte consultar en https://t.me/orionxdev o ver el directorio examples (https://github.com/itolosa/orionx-api-client/tree/master/examples). Saludos y éxito.
