### ISSUE TITLE
cache headers

### ISSUE THREAD

**Issue by nijirija** [itolosa/orionx-api-client#4]
Hola, ¿Cuál debería ser el contenido de cache/cookies.json y headers.json?

Ambos archivos no existen, pero no estoy seguro de como debería armarlos o en dónde buscar los correcto.

```
Traceback (most recent call last):
  File "orionx_test.py", line 6, in <module>
    cookies_filename='cache/cookies.json')
  File "/Library/Python/2.7/site-packages/orionxapi/connection_manager.py", line 31, in client
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
```

Gracias!

**Comment by itolosa** [comment]
Vacíos. Basta con hacer un `$ mkdir cache && touch cache/headers.json && touch cache/cookies.json`. Arreglo en el siguiente commit. Necesito tests urgente. Saludos!

**Comment by nijirija** [comment]
Oh, ya entendí el error. Estoy con Python 2.7 y acá parece que no existe el File not found. 

`"NameError: global name 'FileNotFoundError' is not defined"`


Error mío.

Apenas pueda correr y probar te voy contando

**Comment by nijirija** [comment]
Subí a python3, y ahora tengo este error. ¿Qué puede ser?

(los archivo de cache existen)

```
Traceback (most recent call last):
  File "orionx_marginator2.py", line 6, in <module>
    cookies_filename='cache/cookies.json')
  File "/usr/local/lib/python3.6/site-packages/orionxapi/connection_manager.py", line 29, in client
    headers_tuple = ujson.load(headers_cachefp)
ValueError: Expected object or value
```

**Comment by itolosa** [comment]
Si ahora fue error mío. Elimina los archivos en blanco.

**Comment by itolosa** [comment]
Dejé unos asserts para validar la estructura del archivo en runtime en la version 0.1.2. Por favor actualiza la versión con pip. Los archivos cache estan pensado para guardar los datos de conexion hasta que expiren y asi evitar la saturacion de consultas de inicio de sesion, asi que lo ideal es que no existan, o que esten en blanco ya que ahora si pasa cualquiera de esas dos cosas se crean nuevamente. Asi que para poder actualizar los datos de conexion cuando ya hay archivos caché basta con eliminarlos. Saludos
