### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by nijirija** [itolosa/orionx-api-client#5]
Hola, 
Me están saliendo hartos TimeOut. ¿No te pasa?

`requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.orionx.io', port=443): Read timed out. (read timeout=5)`

**Comment by nijirija** [comment]
Luego de varios intentos, llega al prompt de user/pass, pero se vuelve a quedar un poco pegado y no pide el código de autorización y lanza el siguiente error:


`gql.client.RetryError: Failed 3 retries: HTTPSConnectionPool(host='api.orionx.io', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "orionx_script.py", line 46, in <module>
    cookies_filename='cache/cookies.json')
  File "/usr/local/lib/python3.6/site-packages/orionxapi/connection_manager.py", line 94, in client
    except (Exception, e):
NameError: name 'e' is not defined`


Curiosamente, al ratito llega el mail del código de autorización

**Comment by nijirija** [comment]
Error 100% mio, sorry

**Comment by itolosa** [comment]
Son read timeout, la consulta se envía de todas formas, por eso llega el mail. Que ocurran esos errores son porque la plataforma esta lenta
